#ifndef __APP_FLASH_H__
#define __APP_FLASH_H__

#define APP_FLASH_WR_MILESTONE_SECTOR			(0x0000)

#define APP_FLASH_FIRMWARE_INFO_SECTOR_1		(0x6000)

#define APP_FLASH_FIRMWARE_START_ADDR			(0x80000)
#define APP_FLASH_FIRMWARE_BLOCK_64K_SIZE		(2)

#endif //__APP_FLASH_H__
